### ISSUE TITLE
Linking issue

### ISSUE THREAD

**Issue by shersoni610** [lemenkov/libyuv#12]
Hello, 

I am trying to compile the library on MAC and I have jpeg library installed. However, I get the following
messages:
$ make
[  1%] Linking CXX shared library libyuv.dylib
Undefined symbols for architecture x86_64:
  "_jpeg_CreateDecompress", referenced from:
      libyuv::MJpegDecoder::MJpegDecoder() in mjpeg_decoder.cc.o
      libyuv::MJpegDecoder::MJpegDecoder() in mjpeg_decoder.cc.o
  "_jpeg_abort_decompress", referenced from:
      libyuv::MJpegDecoder::UnloadFrame() in mjpeg_decoder.cc.o
      libyuv::MJpegDecoder::DecodeToBuffers(unsigned char**, int, int) in mjpeg_decoder.cc.o
      libyuv::MJpegDecoder::FinishDecode() in mjpeg_decoder.cc.o
      libyuv::MJpegDecoder::DecodeToCallback(void (*)(void*, unsigned char const* const*, int const*, int), void*, int, int) in mjpeg_decoder.cc.o
  "_jpeg_destroy_decompress", referenced from:
      libyuv::MJpegDecoder::~MJpegDecoder() in mjpeg_decoder.cc.o
      libyuv::MJpegDecoder::~MJpegDecoder() in mjpeg_decoder.cc.o
  "_jpeg_read_header", referenced from:
      libyuv::MJpegDecoder::LoadFrame(unsigned char const*, unsigned long) in mjpeg_decoder.cc.o
  "_jpeg_read_raw_data", referenced from:
      libyuv::MJpegDecoder::DecodeToBuffers(unsigned char**, int, int) in mjpeg_decoder.cc.o
      libyuv::MJpegDecoder::DecodeToCallback(void (*)(void*, unsigned char const* const*, int const*, int), void*, int, int) in mjpeg_decoder.cc.o
  "_jpeg_resync_to_restart", referenced from:
      libyuv::MJpegDecoder::MJpegDecoder() in mjpeg_decoder.cc.o
      libyuv::MJpegDecoder::MJpegDecoder() in mjpeg_decoder.cc.o
  "_jpeg_start_decompress", referenced from:
      libyuv::MJpegDecoder::DecodeToBuffers(unsigned char**, int, int) in mjpeg_decoder.cc.o
      libyuv::MJpegDecoder::StartDecode() in mjpeg_decoder.cc.o
      libyuv::MJpegDecoder::DecodeToCallback(void (*)(void*, unsigned char const* const*, int const*, int), void*, int, int) in mjpeg_decoder.cc.o
  "_jpeg_std_error", referenced from:
      libyuv::MJpegDecoder::MJpegDecoder() in mjpeg_decoder.cc.o
      libyuv::MJpegDecoder::MJpegDecoder() in mjpeg_decoder.cc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libyuv.dylib] Error 1
make[1]: *** [CMakeFiles/yuv_shared.dir/all] Error 2
make: *** [all] Error 2

**Comment by kmilos** [comment]
There's a missing `target_link_libraries( ${ly_lib_shared} ${JPEG_LIBRARY} )` near line 41 of `CMakeLists.txt`.

I guess the static one should be added as well.

**Comment by lemenkov** [comment]
Please submit your issue upstream:

https://chromium.googlesource.com/libyuv/libyuv/

This repository is just an unofficial mirror.
