### ISSUE TITLE
Compiled .so?

### ISSUE THREAD

**Issue by samohd** [lemenkov/libyuv#14]
Can someone provide, or point me towards already compiled android native libraries for latest libyuv. I don't know why these don't get included automatically, but alas... I've searched the world over with no luck finding them. And I've had no luck compiling the code on Windows... finally arriving at "Android builds are only supported on Linux and Mac hosts."

**Comment by kmilos** [comment]
> And I've had no luck compiling the code on Windows...

You can perhaps take inspiration from [mingw ](https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-libyuv) or [vcpkg](https://github.com/Microsoft/vcpkg/tree/master/ports/libyuv) patches.

**Comment by lemenkov** [comment]
Please submit your issue upstream:

https://chromium.googlesource.com/libyuv/libyuv/

This repository is just an unofficial mirror.
