### ISSUE TITLE
libyuv_internal.lib is not able to link with Visual Studio 2015.

### ISSUE THREAD

**Issue by njain34** [lemenkov/libyuv#15]
I have followed https://chromium.googlesource.com/libyuv/libyuv/+/refs/heads/main/docs/getting_started.md
and build 32-bit libyuv.lib for Windows.

I was able to build this with only "stable" version branch of libyuv.

After build success when I use libyuv.lib in my Visual Studio : Configuration Properties -> Linker -> General -> Input -> additional dependencies.

I get linking error while building as : 
libyuv_internal.lib : fatal error LNK1107: invalid or corrupt file: cannot read at 0x8EE8

I did search for the this error: This is says you havn't passed lib, might be you have passed dll. But my build has no error and successfully created libyuv_internal.lib.

Any help will be appreciated.
Kindly help me getting the solution. Or guide me where I can ask this question.

**Comment by lemenkov** [comment]
Please submit your issue upstream:

https://chromium.googlesource.com/libyuv/libyuv/

This repository is just an unofficial mirror.
