### ISSUE TITLE
cannot compile for android

### ISSUE THREAD

**Issue by chenzh2017** [lemenkov/libyuv#2]
I use cygwin compile the libyuv for android,like this:
`jni/source/row_common.cc: In function 'void libyuv::YuvPixel(uint8, uint8, uint8, uint8*, uint8*, uint8*, const libyuv::YuvConstants*)':
jni/source/row_common.cc:1068:36: error: invalid types 'const uvec8 {aka __vector(16) unsigned char const}[int]' for array subscript
`
my ndk is ndk-10b

**Comment by lemenkov** [comment]
This repository is just a private fork. Please ask upstream.
