### ISSUE TITLE
Converting from 10-bit RGB to float

### ISSUE THREAD

**Issue by WindowsNT** [lemenkov/libyuv#21]
I successfully loaded a P010 video sample which returns me a 10-bit RGB structure:

```
struct ar30
{
    unsigned b : 10;
    unsigned g : 10;
    unsigned r : 10;
    unsigned a : 2;
};
```

How should I convert this to a 128 bit float array to match my HDR settings of the Direct3D device? I tried dividing by 1024 to convert to [0,4] or even by 256 to convert to [0,1] but I have incorrect luminance in the RGB result.

**Comment by lemenkov** [comment]
Please submit your issue upstream:

https://chromium.googlesource.com/libyuv/libyuv/

This repository is just an unofficial mirror.
