### ISSUE TITLE
Compilation error in arm processor

### ISSUE THREAD

**Issue by hy-chao** [lemenkov/libyuv#22]
g++ -c -fno-exceptions -Iinclude/ source/scale_neon64.cc -o source/scale_neon64.o
/tmp/ccsKoCAr.s: Assembler messages:
/tmp/ccsKoCAr.s:710: Error: operand mismatch -- `mov v0.8h,v4.8h'
/tmp/ccsKoCAr.s:710: Info:    did you mean this?
/tmp/ccsKoCAr.s:710: Info:      mov v0.8b,v4.8b
/tmp/ccsKoCAr.s:710: Info:    other valid variant(s):
/tmp/ccsKoCAr.s:710: Info:      mov v0.16b,v4.16b
/tmp/ccsKoCAr.s:711: Error: operand mismatch -- `mov v1.8h,v5.8h'
/tmp/ccsKoCAr.s:711: Info:    did you mean this?
/tmp/ccsKoCAr.s:711: Info:      mov v1.8b,v5.8b
/tmp/ccsKoCAr.s:711: Info:    other valid variant(s):
/tmp/ccsKoCAr.s:711: Info:      mov v1.16b,v5.16b
/tmp/ccsKoCAr.s:761: Error: operand mismatch -- `mov v2.8h,v0.8h'
/tmp/ccsKoCAr.s:761: Info:    did you mean this?
/tmp/ccsKoCAr.s:761: Info:      mov v2.8b,v0.8b
/tmp/ccsKoCAr.s:761: Info:    other valid variant(s):
/tmp/ccsKoCAr.s:761: Info:      mov v2.16b,v0.16b
/tmp/ccsKoCAr.s:821: Error: operand mismatch -- `mov v0.8h,v2.8h'
/tmp/ccsKoCAr.s:821: Info:    did you mean this?
/tmp/ccsKoCAr.s:821: Info:      mov v0.8b,v2.8b
/tmp/ccsKoCAr.s:821: Info:    other valid variant(s):
/tmp/ccsKoCAr.s:821: Info:      mov v0.16b,v2.16b
/tmp/ccsKoCAr.s:827: Error: operand mismatch -- `mov v0.8h,v4.8h'
/tmp/ccsKoCAr.s:827: Info:    did you mean this?
/tmp/ccsKoCAr.s:827: Info:      mov v0.8b,v4.8b
/tmp/ccsKoCAr.s:827: Info:    other valid variant(s):
/tmp/ccsKoCAr.s:827: Info:      mov v0.16b,v4.16b
/tmp/ccsKoCAr.s:830: Error: operand mismatch -- `mov v0.8h,v4.8h'
/tmp/ccsKoCAr.s:830: Info:    did you mean this?
/tmp/ccsKoCAr.s:830: Info:      mov v0.8b,v4.8b
/tmp/ccsKoCAr.s:830: Info:    other valid variant(s):
/tmp/ccsKoCAr.s:830: Info:      mov v0.16b,v4.16b
/tmp/ccsKoCAr.s:831: Error: operand mismatch -- `mov v1.8h,v5.8h'
/tmp/ccsKoCAr.s:831: Info:    did you mean this?
/tmp/ccsKoCAr.s:831: Info:      mov v1.8b,v5.8b
/tmp/ccsKoCAr.s:831: Info:    other valid variant(s):
/tmp/ccsKoCAr.s:831: Info:      mov v1.16b,v5.16b
/tmp/ccsKoCAr.s:1082: Error: operand mismatch -- `mov v0.8h,v4.8h'
/tmp/ccsKoCAr.s:1082: Info:    did you mean this?
/tmp/ccsKoCAr.s:1082: Info:     mov v0.8b,v4.8b
/tmp/ccsKoCAr.s:1082: Info:    other valid variant(s):
/tmp/ccsKoCAr.s:1082: Info:     mov v0.16b,v4.16b
/tmp/ccsKoCAr.s:1083: Error: operand mismatch -- `mov v1.8h,v5.8h'
/tmp/ccsKoCAr.s:1083: Info:    did you mean this?
/tmp/ccsKoCAr.s:1083: Info:     mov v1.8b,v5.8b
/tmp/ccsKoCAr.s:1083: Info:    other valid variant(s):
/tmp/ccsKoCAr.s:1083: Info:     mov v1.16b,v5.16b
linux.mk:64: recipe for target 'source/scale_neon64.o' failed
make: *** [source/scale_neon64.o] Error 1

**Comment by lemenkov** [comment]
Please submit your issue upstream:

https://chromium.googlesource.com/libyuv/libyuv/

This repository is just an unofficial mirror.
