### ISSUE TITLE
why libyuv::I420ToRGB24 result is diff from opencv COLOR_YUV2RGB_I420

### ISSUE THREAD

**Issue by lhxy1991** [lemenkov/libyuv#23]
I use libyuv and opencv to convert I420 to RGB.But I get different result. Channel R and channel B are opposite。
` cv::Mat imgRGB = cv::Mat::zeros(720, 1280, CV_8UC3);
        //cv::Mat的默认存储方式是BGR，所以I420ToRGB24以后的顺序是RGB
        libyuv::I420ToRGB24(mCurFrameBuffer, 1280, mCurFrameBuffer + 1280 * 720, 640,
                            mCurFrameBuffer + 1280 * 720 * 5 / 4, 640, imgRGB.data, 1280 * 3, 1280,
                            720);
        LOGE("data0=%d,%d,%d,%d,%d,%d",imgRGB.data[0],imgRGB.data[1],imgRGB.data[2],imgRGB.data[3],imgRGB.data[4],imgRGB.data[5]);
        imgRGB.release();
        cv::Mat mYUVFrame=cv::Mat(1080,1280,CV_8UC1,mCurFrameBuffer);
        cvtColor(mYUVFrame,imgRGB,COLOR_YUV2RGB_I420);
        LOGE("data1=%d,%d,%d,%d,%d,%d",imgRGB.data[0],imgRGB.data[1],imgRGB.data[2],imgRGB.data[3],imgRGB.data[4],imgRGB.data[5]);
`
I find that the result of libyuv is ( 183,200,100),but the result of opencv is (100,200,183).
Why i get this diffent?

**Comment by lemenkov** [comment]
Please submit your issue upstream:

https://chromium.googlesource.com/libyuv/libyuv/

This repository is just an unofficial mirror.
