### ISSUE TITLE
Is that a typo in ScaleUVRowDown2_C function

### ISSUE THREAD

**Issue by TsaiHongYan** [lemenkov/libyuv#24]
Hi:
 I'm not sure that in ScaleUVRowDown2_C function <src += 2;> is right. 
 I try to 1920 * 1080 NV12 picture scale to 960 * 540 NV12 called NV12Scale.
 I found the uv channel is wrong. After debugging the code, 
I found the code is probably wrong. I changed the code src +=4;
After changing, I run my project again. The uv channel is right.
So I wanna know my modify is right? if wrong, please tell me what right changing is. 
Thank you
Best regards

**Comment by lemenkov** [comment]
Hello!
Please submit your issue upstream:

https://chromium.googlesource.com/libyuv/libyuv/

This repository is just an unofficial personal mirror.
