### ISSUE TITLE
The MirrorRow_NEON method in row_neon64.cc  may cause memory overruns

### ISSUE THREAD

**Issue by fxslltfxl** [lemenkov/libyuv#25]
dump:
#00 pc 00000000000528dc /data/app/~~r0QaG9SaRnWtp7JB809NlQ==/com.tencent.wemeet.app-35nEGgvowN0g374dg7n9mg==/lib/arm64/libyuv.so (MirrorRow_NEON (jni/source/row_neon64.cc:1050-1051)+40) [arm64-v8a::95aad96840c61da2ac93f479a17c659b]
1#01 pc 0000000000038888 RotatePlane180 (jni/source/rotate.cc:214) [arm64-v8a]
2#02 pc 0000000000038f14 RotatePlane (jni/source/rotate.cc:412) [arm64-v8a]

In this code, memory transgressions can occur in the following situations: 
 
If width is not a multiple of 32, then on the last iteration of the loop, the ldr instruction may try to load data from the memory location before the src pointer, which may cause memory to cross the line. For example, if width is 35, then on the last iteration, the src pointer will be subtracted by 32, resulting in an attempt to load data from three bytes before the src pointer. 
 
If the src or dst pointer points to an area of memory that is not large enough to hold width bytes of data, it may also cause a memory transgression when reading or writing data. 
 
If the src or dst Pointers are not aligned by 32 bytes, the ldr and st1 instructions can result in unaligned memory access, which can cause an error on some systems. 
 
To avoid these problems, you should make sure that width is a multiple of 32, that the src and dst Pointers point to a large enough area of memory, and that both Pointers are aligned by 32 bytes.

**Comment by lemenkov** [comment]
Hello @fxslltfxl 
This repository is just an informal mirror. Please report this issue [upstream](https://chromium.googlesource.com/libyuv/libyuv/).
