### ISSUE TITLE
ScaleCols_C question

### ISSUE THREAD

**Issue by victorygogogo** [lemenkov/libyuv#3]
who can give me some explaination about this function ?

// Scales a single row of pixels using point sampling.
void ScaleCols_C(uint8* dst_ptr, const uint8* src_ptr,
                 int dst_width, int x, int dx) {
  int j;
  for (j = 0; j < dst_width - 1; j += 2) {
    dst_ptr[0] = src_ptr[x >> 16];
    x += dx;
    dst_ptr[1] = src_ptr[x >> 16];
    x += dx;
    dst_ptr += 2;
  }
  if (dst_width & 1) {
    dst_ptr[0] = src_ptr[x >> 16];
  }
}

**Comment by lemenkov** [comment]
This repository is just a private fork. Please ask upstream for any clarifications.
