### ISSUE TITLE
Instruction Set   cannot support  for X64 - Windows -VS2015

### ISSUE THREAD

**Issue by ib198669** [lemenkov/libyuv#6]
In  X64 - Windows -VS2015   ,  Instruction Set  such as SSE / AVX   seems to be not  effective  .As a result ,  transform from RGB to YUV    ,  waste  8ms  in a   1080p Frame . this bug  only occurs on X64-Windows,  in X86-Windows   and  X86 or X64 in Linux  it performs   OK .
        Could you tell me how to figure the bug??  thanks very much.

**Comment by lemenkov** [comment]
This repo is just an unofficial mirror among many others. Please report this issue upstream:

https://chromium.googlesource.com/libyuv/libyuv/
