### ISSUE TITLE
ScaleARGB 是否支持盒子滤波

### ISSUE THREAD

**Issue by snailguo666** [lemenkov/libyuv#9]
ScaleARGB 这函数里面，说到ARGB does not support box filter yet, but allow the user to pass it，但是实现里面又有
 if (dx == 0x40000 && filtering == kFilterBox) {
          // Optimized 1/4 box downsample.
          ScaleARGBDown4Box(src_width, src_height, clip_width, clip_height,
                            src_stride, dst_stride, src, dst, x, dx, y, dy);
          return;
        }
为什么呢？

**Comment by lemenkov** [comment]
Please send your report to upstream project. This repo is just a personal mirror.

https://chromium.googlesource.com/libyuv/libyuv
